// Generated by CoffeeScript 1.8.0
(function() {
  var UserService;

  UserService = (function() {
    UserService.headers = {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    };

    UserService.defaultConfig = {
      headers: UserService.headers
    };

    function UserService($log, $http, $q) {
      this.$log = $log;
      this.$http = $http;
      this.$q = $q;
      this.$log.debug("constructing UserService");
    }

    UserService.prototype.listUsers = function() {
      var deferred;
      this.$log.debug("listUsers()");
      deferred = this.$q.defer();
      this.$http.get("/users").success((function(_this) {
        return function(data, status, headers) {
          _this.$log.info("Successfully listed Users - status " + status);
          _this.$log.info("Successfully listed Users - data " + data);
          return deferred.resolve(data);
        };
      })(this)).error((function(_this) {
        return function(data, status, headers) {
          _this.$log.error("Failed to list Users - status " + status);
          return deferred.reject(data);
        };
      })(this));
      return deferred.promise;
    };

    UserService.prototype.createUser = function(user) {
      var deferred;
      this.$log.debug("createUser " + (angular.toJson(user, true)));
      this.$log.debug("createUser " + user.firstname + " " + user.lastname);
      deferred = this.$q.defer();
      this.$http.post('/users', user).success((function(_this) {
        return function(data, status, headers) {
          _this.$log.info("Successfully created User - status " + status);
          return deferred.resolve(data);
        };
      })(this)).error((function(_this) {
        return function(data, status, headers) {
          _this.$log.error("Failed to create user - status " + status);
          return deferred.reject(data);
        };
      })(this));
      return deferred.promise;
    };

    UserService.prototype.updateUser = function(user) {
      var deferred;
      this.$log.debug("updateUser " + (angular.toJson(user, true)));
      this.$log.debug("updateUser " + user.firstname + " " + user.lastname);
      deferred = this.$q.defer();
      this.$http.put('/users/' + user.id, user).success((function(_this) {
        return function(data, status, headers) {
          _this.$log.info("Successfully update User - status " + status);
          return deferred.resolve(data);
        };
      })(this)).error((function(_this) {
        return function(data, status, headers) {
          _this.$log.error("Failed to update user - status " + status);
          return deferred.reject(data);
        };
      })(this));
      return deferred.promise;
    };

    UserService.prototype.findUser = function(firstname) {
      var deferred;
      this.$log.debug("findUser()");
      deferred = this.$q.defer();
      this.$http.get("/users/" + firstname).success((function(_this) {
        return function(data, status, headers) {
          _this.$log.info("Successfully find User - status " + status);
          _this.$log.info("Successfully find User - data " + data);
          return deferred.resolve(data);
        };
      })(this)).error((function(_this) {
        return function(data, status, headers) {
          _this.$log.error("Failed to find User - status " + status);
          return deferred.reject(data);
        };
      })(this));
      return deferred.promise;
    };

    UserService.prototype.deleteUser = function(firstname) {
      var deferred;
      this.$log.debug("deleteUser()");
      deferred = this.$q.defer();
      this.$http["delete"]("/users/" + firstname).success((function(_this) {
        return function(data, status, headers) {
          _this.$log.info("Successfully Delete User - status " + status);
          _this.$log.info("Successfully Delete User - data " + data);
          return deferred.resolve(data);
        };
      })(this)).error((function(_this) {
        return function(data, status, headers) {
          _this.$log.error("Failed to Delete User - status " + status);
          return deferred.reject(data);
        };
      })(this));
      return deferred.promise;
    };

    return UserService;

  })();

  servicesModule.service('UserService', UserService);

}).call(this);
