// Generated by CoffeeScript 1.8.0
(function() {
  var app, dependencies;

  dependencies = ['ngRoute', 'ui.bootstrap', 'myApp.filters', 'myApp.services', 'myApp.controllers', 'myApp.directives', 'myApp.common', 'ngTable', 'myApp.routeConfig'];

  app = angular.module('myApp', dependencies);

  angular.module('myApp.routeConfig', ['ngRoute']).config(function($routeProvider) {
    return $routeProvider.when('/users', {
      templateUrl: 'views/user-list.html'
    }).when('/user/create', {
      templateUrl: 'views/user-creation.html'
    }).when('/delete/:firstname', {
      templateUrl: 'views/user-delete.html'
    }).when('/edit/:firstname', {
      templateUrl: 'views/user-edit.html'
    }).otherwise({
      redirectTo: '/users'
    });
  });

  this.commonModule = angular.module('myApp.common', []);

  this.controllersModule = angular.module('myApp.controllers', []);

  this.servicesModule = angular.module('myApp.services', []);

  this.modelsModule = angular.module('myApp.models', []);

  this.directivesModule = angular.module('myApp.directives', []);

  this.filtersModule = angular.module('myApp.filters', []);

}).call(this);
